name: smart_waste_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.5.1
  smooth_page_indicator: ^1.1.0

  logger: ^2.0.0

  

  cupertino_icons: ^1.0.8

  # ✅ State management (Clean Architecture friendly)
  flutter_riverpod: ^2.5.1

  # ✅ Routing
  go_router: ^14.2.7

  # ✅ Local DB (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # ✅ Helpers / Clean code
  equatable: ^2.0.5
  uuid: ^4.5.1
  intl: ^0.19.0

  # ✅ Typography (pixel-perfect UI)
  google_fonts: ^6.2.1

  # ✅ Local key/value storage
  shared_preferences: ^2.3.2

  # ✅ Networking
  http: ^1.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # ✅ Hive model generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
